### ISSUE TITLE
[FEATURE] Generate runnable binary artifact

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk#11]
### Is your feature request related to a problem?
The only way to run the SDK is via ./gradlew run. 
This does not scale, we need to publish a runnable binary artifact

**Comment by dblock** [comment]
Publish -SNAPSHOT(s) to maven earlier than later.

**Comment by minalsha** [comment]
@saratvemulapalli  to create a separate issue for publishing the artifacts to Maven.

**Comment by saratvemulapalli** [comment]
https://github.com/opensearch-project/opensearch-sdk/issues/75
