### ISSUE TITLE
[FEATURE] Add Java docs and mandate for all new classes

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/opensearch-sdk#27]
### Is your feature request related to a problem?
We are missing Java docs for this repository. 

### What solution would you like?
Lets add support for Java docs and mandate all new classes to have them. 
We could run this check as part of the PR check workflow.

**Comment by dbwiddis** [comment]
+1. We are small enough right now to fix this without too much effort.

**Comment by dbwiddis** [comment]
When I submitted a PR on the core repo yesterday the PR template included a check-off for Javadocs.  I'll add that to this repo; may not be an automated check but it will be something that submitters will see when they submit a PR, and should prompt code reviewers to do so as well.

Also can we be clear on the policy for Javadocs?  My thoughts:
 - Required for all classes
 - Required for all `public` and `protected` methods, _with the exception of getters and setters_ where the only javadoc would be "gets the foo"; "sets the foo".  Optional for private methods if the usage isn't obvious.
   - First line should be short and end in a period.
   - Separate paragraphs with `<p>`
   - `@param` required if any parameters. Explicitly state if null is allowed.
   - `@param` required for generics, e.g., `<T>`
   - `@return` required including what return values represent error conditions. Explicitly state if null is returned.
   - `@throws` required for runtime exceptions that aren't caught

**Comment by dbwiddis** [comment]
I should have added to the above list. If a method overrides a method in a superclass, it automatically inherits that javadoc so it isn't required -- but can be added with the inheritdoc annotation if there's anything additional to say that the superclass/interface javadoc doesn't cover.

**Comment by dbwiddis** [comment]
https://github.com/plume-lib/require-javadoc

**Comment by peternied** [comment]
I would rather add dependencies on maintained components, I'd cast my vote with either `require-javadoc` or `checkstyle`.

If there are missing features in either tool, this would be a good reason to improve them with a proposal and pull request(s) to unblock adoption.

**Comment by saratvemulapalli** [comment]
> @saratvemulapalli and @owaiskazi19 what are your thoughts?
I would always prefer relying on standard implementation vs something for us to maintain down the line. 
I would go with `require-javadoc`, also take our learnings to opensearch repository.

**Comment by owaiskazi19** [comment]
> @saratvemulapalli and @owaiskazi19 what are your thoughts?

Discussed offline. +1 to @saratvemulapalli

**Comment by dbwiddis** [comment]
OK, will switch to require-javadoc for this repo, and get some lessons learned and if we like it suggest for the main repo.

FYI, I requested https://github.com/plume-lib/require-javadoc/issues/143 to help minimize trivial documentation.
