### ISSUE TITLE
[FEATURE] Add a new-line linter in the current CI workflow

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/opensearch-sdk#46]
### Is your feature request related to a problem?
Coming from https://github.com/opensearch-project/OpenSearch/issues/2857. Add a new-line linter to make sure all files end with a single newline. This is a POSIX standard, read more https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline

### What solution would you like?
Can use https://github.com/fernandrone/linelint/releases for the workflow.

### What alternatives have you considered?
_A clear and concise description of any alternative solutions or features you've considered._

### Do you have any additional context?
_Add any other context or screenshots about the feature request here._

**Comment by dbwiddis** [comment]
I don't like that the linter complains about it but doesn't fix it.  Adding the line to spotless as suggested above would fix it (and also fail it on spotless check but with a more helpful message how to fix!)
