### ISSUE TITLE
[FEATURE] Review existing Requests and Responses in AD plugin to evaluate how SDK handlers need to be updated

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk#62]
### Is your feature request related to a problem?

As noted in #22, having an implementation of _Client_ is necessary for the plugin (and future extension) functionality.  Additionally, the _AbstractClient_ implementation is sufficient for our (near term) needs.

The more complex work is in reviewing the existing calls to `execute()` (or `index()`, `search()`, or `get()` which delegate to `execute()`, the arguments the existing plugin passes to those calls, and determining if additional work will be needed to modify them in an extension/transport/REST environment.

### What solution would you like?

The code extracts listed below should be reviewed to determine if any changes to their implementations of `Request` and `Response` are required, and/or if additional Response Handler classes are needed.

### What alternatives have you considered?

I've considered doing nothing until testing, because some of the code will probably work, and we'd find out what was broken later.  But looking at it now will be more helpful.

### Do you have any additional context?

Permalinks to code below (representative code shown; there are many many more but most are similar to the below):

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java#L273-L291

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java#L459-L471

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java#L485

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorJobRunner.java#L548-L558

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java#L123-L144

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java#L298-L309

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/AnomalyDetectorProfileRunner.java#L382-L391

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/EntityProfileRunner.java#L93-L120

https://github.com/opensearch-project/anomaly-detection/blob/9f6a5abb9652fb010decde8778c56c292eac90e2/src/main/java/org/opensearch/ad/transport/GetAnomalyDetectorTransportAction.java#L135-L150

**Comment by minalsha** [comment]
Closing since this would be covered as part of #66  that @owaiskazi19  has.
